spring.application.name=ex03-backend
server.port=${SERVER_PORT:8083}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ex03db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ex03user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ex03pass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
