spring.application.name=catalog-service
server.port=${SERVER_PORT:8091}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ex04db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ex04user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ex04pass}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
